/*
 * API REST EXTERNA de queesticfent
 * Conjunt de Serveis REST de queesticfent per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.queesticfent.apiexterna.client.api;

import org.fundaciobit.queesticfent.apiexterna.client.services.ApiClient;
import org.fundaciobit.queesticfent.apiexterna.client.services.ApiException;
import org.fundaciobit.queesticfent.apiexterna.client.model.Modificacio;
import org.fundaciobit.queesticfent.apiexterna.client.model.ModificacionsConstants;
import org.fundaciobit.queesticfent.apiexterna.client.model.RestExceptionInfo;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ModificacionsApi
 */
public class ModificacionsApiTest {

    

    /**
     * Afegeix una nova entrada
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTest() throws ApiException {
        
        final ModificacionsApi api = getApi();
        
        Modificacio modificacio = new Modificacio();
        modificacio.setUsuariID("fbosch");
        modificacio.setDada1("Dada 1 XXX");
        modificacio.setData(new Date().toInstant().atOffset(ZoneOffset.UTC));
        modificacio.setLanguage("ca");
        modificacio.setProjecteID((long) 13);
        
        
        Long response = api.add(modificacio);
        
        System.out.println("Response = "+response);
        

        // TODO: test validations
    }
    
    
    private ModificacionsApi getApi() {

        String host = "http://fbosch:8080/queesticfentapi/externa";
        String username = "testapp";
        String password = "testapp";

        ApiClient client = new ApiClient();
        client.setBasePath(host);
        client.setUsername(username);
        client.setPassword(password);

        ModificacionsApi api = new ModificacionsApi(client);

        return api;

    }
    
}
