_projectName_=queesticfent
_projectPrefix_=qef
qef_accio=accio
qef_accio_PK=qef_accio_pk
qef_departament=departamen
qef_departament_PK=qef_departament_pk
qef_entrada=entrada
qef_entrada_PK=qef_entrada_pk
qef_festiu=festiu
qef_festiu_PK=qef_festiu_pk
qef_fitxer=fitxer
qef_fitxer_PK=qef_fitxer_pk
qef_idioma=idioma
qef_idioma_PK=qef_idioma_pk
qef_modificacioqueesticfent=modifqef
qef_modificacioqueesticfent_PK=qef_modificacioqueesticfent_pk
qef_personalprojecte=persproj
qef_personalprojecte_PK=qef_personalprojecte_pk
qef_projecte=projecte
qef_projecte_PK=qef_projecte_pk
qef_traduccio=traduccio
qef_traduccio_PK=qef_traduccio_pk
qef_traducciomap=traducmap
qef_traducciomap_PK=qef_traducmap_pk
qef_traducciomap_PK=qef_traducmap_pk
qef_usuari=usuari
qef_usuari_PK=qef_usuari_pk
qef_usuaridepartament=usudepart
qef_usuaridepartament_PK=qef_usuaridepartament_pk
