/*
 * API REST EXTERNA de queesticfent
 * Conjunt de Serveis REST de queesticfent per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.queesticfent.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.fundaciobit.queesticfent.apiexterna.client.model.ModificacioRest;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetModificacionsResponse
 */
@JsonPropertyOrder({
  GetModificacionsResponse.JSON_PROPERTY_MODIFICACIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetModificacionsResponse {
  public static final String JSON_PROPERTY_MODIFICACIONS = "modificacions";
  private List<ModificacioRest> modificacions;

  public GetModificacionsResponse() {
  }

  public GetModificacionsResponse modificacions(List<ModificacioRest> modificacions) {
    
    this.modificacions = modificacions;
    return this;
  }

  public GetModificacionsResponse addModificacionsItem(ModificacioRest modificacionsItem) {
    if (this.modificacions == null) {
      this.modificacions = new ArrayList<>();
    }
    this.modificacions.add(modificacionsItem);
    return this;
  }

   /**
   * Get modificacions
   * @return modificacions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFICACIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ModificacioRest> getModificacions() {
    return modificacions;
  }


  @JsonProperty(JSON_PROPERTY_MODIFICACIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModificacions(List<ModificacioRest> modificacions) {
    this.modificacions = modificacions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetModificacionsResponse getModificacionsResponse = (GetModificacionsResponse) o;
    return Objects.equals(this.modificacions, getModificacionsResponse.modificacions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modificacions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetModificacionsResponse {\n");
    sb.append("    modificacions: ").append(toIndentedString(modificacions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

