/*
 * API REST EXTERNA de queesticfent
 * Conjunt de Serveis REST de queesticfent per ser accedits des de l'exterior
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: otae@fundaciobit.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.fundaciobit.queesticfent.apiexterna.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Bean que inclou informació d&#39;una entrada.
 */
@JsonPropertyOrder({
  ModificacioRest.JSON_PROPERTY_MODIFICACIO_I_D,
  ModificacioRest.JSON_PROPERTY_ACCIO_I_D,
  ModificacioRest.JSON_PROPERTY_USUARI_I_D,
  ModificacioRest.JSON_PROPERTY_PROJECTE_I_D,
  ModificacioRest.JSON_PROPERTY_DADA1,
  ModificacioRest.JSON_PROPERTY_DADA2,
  ModificacioRest.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ModificacioRest {
  public static final String JSON_PROPERTY_MODIFICACIO_I_D = "modificacioID";
  private Long modificacioID;

  public static final String JSON_PROPERTY_ACCIO_I_D = "accioID";
  private Long accioID;

  public static final String JSON_PROPERTY_USUARI_I_D = "usuariID";
  private String usuariID;

  public static final String JSON_PROPERTY_PROJECTE_I_D = "projecteID";
  private Long projecteID;

  public static final String JSON_PROPERTY_DADA1 = "dada1";
  private String dada1;

  public static final String JSON_PROPERTY_DADA2 = "dada2";
  private String dada2;

  public static final String JSON_PROPERTY_DATA = "data";
  private OffsetDateTime data;

  public ModificacioRest() {
  }

  public ModificacioRest modificacioID(Long modificacioID) {
    
    this.modificacioID = modificacioID;
    return this;
  }

   /**
   * Get modificacioID
   * @return modificacioID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODIFICACIO_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getModificacioID() {
    return modificacioID;
  }


  @JsonProperty(JSON_PROPERTY_MODIFICACIO_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModificacioID(Long modificacioID) {
    this.modificacioID = modificacioID;
  }


  public ModificacioRest accioID(Long accioID) {
    
    this.accioID = accioID;
    return this;
  }

   /**
   * Get accioID
   * @return accioID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCIO_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccioID() {
    return accioID;
  }


  @JsonProperty(JSON_PROPERTY_ACCIO_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccioID(Long accioID) {
    this.accioID = accioID;
  }


  public ModificacioRest usuariID(String usuariID) {
    
    this.usuariID = usuariID;
    return this;
  }

   /**
   * Get usuariID
   * @return usuariID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USUARI_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsuariID() {
    return usuariID;
  }


  @JsonProperty(JSON_PROPERTY_USUARI_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsuariID(String usuariID) {
    this.usuariID = usuariID;
  }


  public ModificacioRest projecteID(Long projecteID) {
    
    this.projecteID = projecteID;
    return this;
  }

   /**
   * Get projecteID
   * @return projecteID
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECTE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProjecteID() {
    return projecteID;
  }


  @JsonProperty(JSON_PROPERTY_PROJECTE_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjecteID(Long projecteID) {
    this.projecteID = projecteID;
  }


  public ModificacioRest dada1(String dada1) {
    
    this.dada1 = dada1;
    return this;
  }

   /**
   * Get dada1
   * @return dada1
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DADA1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDada1() {
    return dada1;
  }


  @JsonProperty(JSON_PROPERTY_DADA1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDada1(String dada1) {
    this.dada1 = dada1;
  }


  public ModificacioRest dada2(String dada2) {
    
    this.dada2 = dada2;
    return this;
  }

   /**
   * Get dada2
   * @return dada2
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DADA2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDada2() {
    return dada2;
  }


  @JsonProperty(JSON_PROPERTY_DADA2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDada2(String dada2) {
    this.dada2 = dada2;
  }


  public ModificacioRest data(OffsetDateTime data) {
    
    this.data = data;
    return this;
  }

   /**
   * Data de l&#39;entrada
   * @return data
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(OffsetDateTime data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModificacioRest modificacioRest = (ModificacioRest) o;
    return Objects.equals(this.modificacioID, modificacioRest.modificacioID) &&
        Objects.equals(this.accioID, modificacioRest.accioID) &&
        Objects.equals(this.usuariID, modificacioRest.usuariID) &&
        Objects.equals(this.projecteID, modificacioRest.projecteID) &&
        Objects.equals(this.dada1, modificacioRest.dada1) &&
        Objects.equals(this.dada2, modificacioRest.dada2) &&
        Objects.equals(this.data, modificacioRest.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(modificacioID, accioID, usuariID, projecteID, dada1, dada2, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModificacioRest {\n");
    sb.append("    modificacioID: ").append(toIndentedString(modificacioID)).append("\n");
    sb.append("    accioID: ").append(toIndentedString(accioID)).append("\n");
    sb.append("    usuariID: ").append(toIndentedString(usuariID)).append("\n");
    sb.append("    projecteID: ").append(toIndentedString(projecteID)).append("\n");
    sb.append("    dada1: ").append(toIndentedString(dada1)).append("\n");
    sb.append("    dada2: ").append(toIndentedString(dada2)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

